#!/usr/bin/env ruby

require 'rubygems'
require 'bundler'
require 'json'

Bundler.setup

require 'nats/client'

module DeaTool
  class << self

    def echo_reply(subj, msg = nil)
      NATS.start(:uri => 'nats://localhost:4444') do
        NATS.request(subj, msg) do |msg|
          puts msg
          EM.stop
        end
      end
    end

    def publish(subj, msg = nil)
      NATS.start(:uri => 'nats://localhost:4444') do
        NATS.publish(subj, msg)
        EM.add_timer(0.25) { EM.stop } #give message time to fly.
      end
    end

    def get_status
      echo_reply('dea.status')
    end

    def hm_start
      publish('healthmanager.start')
    end

    def dea_locate
      publish('dea.locate')
    end

    def dea_stop
      publish('dea.stop')
    end

    def router_start
      publish('router.start')
    end

    def stop_app
      NATS.start(:uri => 'nats://localhost:4444') do
        NATS.subscribe('dea.heartbeat') { |msg|
          msg = JSON.parse(msg)
          droplet = msg['droplets'][0]

           NATS.publish('dea.stop', droplet.to_json)
            EM.add_timer(0.25) { EM.stop } #give message time to fly.
        }
      end
    end

    def update_app_uris
      update_msg = {"droplet"=>15,"name"=>"fizzle1","uris"=>["fizzle1.vcap.me","yomama.vcap.me"],"runtime"=>"ruby18","framework"=>"sinatra","sha1"=>"0856b85c40e70a5a2efc50ebf4a5cda04cda6297","executableFile"=>"/var/vcap/shared/droplets/0856b85c40e70a5a2efc50ebf4a5cda04cda6297","executableUri"=>"/staged_droplets/15/0856b85c40e70a5a2efc50ebf4a5cda04cda6297","version"=>"0856b85c40e70a5a2efc50ebf4a5cda04cda6297-1","services"=>[],"limits"=>{"mem"=>128,"disk"=>2048,"fds"=>256},"env"=>[],"users"=>["talg@vmware.com"]}
      publish('dea.update', update_msg.to_json)
    end

    def find_app
      NATS.start(:uri => 'nats://localhost:4444') do
        NATS.subscribe('dea.heartbeat') do |msg|
          msg = JSON.parse(msg)
          droplet = msg['droplets'][0]
          NATS.request('dea.find.droplet', droplet.to_json) do |response|
            puts response
            EM.stop
          end
        end
      end
    end

    def start_app
      NATS.start(:uri => 'nats://localhost:4444') do
        start_msg =
          {"droplet"=>19, "name"=>"baz", "uris"=>["baz.vcap.me"], "runtime"=>"ruby18", "framework"=>"sinatra", "sha1"=>"1544e9fe2804deeeee29d68a798639b727054f44", "executableFile"=>"/var/vcap/shared/droplets/1544e9fe2804deeeee29d68a798639b727054f44", "executableUri"=>"http://127.0.0.1:9022/staged_droplets/19/1544e9fe2804deeeee29d68a798639b727054f44", "version"=>"1544e9fe2804deeeee29d68a798639b727054f44-1", "services"=>[], "limits"=>{"mem"=>128, "disk"=>2048, "fds"=>256}, "env"=>[], "users"=>["talg@vmware.com"], "index"=>0}.to_json

        NATS.subscribe("dea.advertise") { |msg|
          dea_id = JSON.parse(msg)["id"]
          NATS.publish("dea.#{dea_id}.start", start_msg)
          EM.add_timer(0.25) { EM.stop } #give message time to fly.
        }
        NATS.publish("dea.locate")
      end
    end
  end
end

puts "start app"
DeaTool.start_app

