# See src/lib/dea/config.rb for optional config values.

# Base directory for dea, application directories, dea temp files, etc. are all relative to this.
base_dir: /home/work/dea_ng/tmp/dea_ng

local_route: 10.36.166.28

domain: vcap.me

resources:
  memory_mb: 20480
  memory_overcommit_factor: 2
  disk_mb: 20480
  disk_overcommit_factor: 2

# The this flag determines whether or not this DEA should only host
# production apps. (default: false)
only_production_apps: false

nats_uri: nats://n_user:n_passwd@10.36.166.28:8444/

pid_filename: /home/work/dea_ng/status/dea_ng.pid

warden_socket: /home/work/warden/warden/status/warden.sock

evacuation_delay_secs: 5

index: 0

staging:
  enabled: true
  platform_config:
    cache: /home/work/dea_ng/data/stager/package_cache/ruby
  environment:
    PATH: /home/work/ruby193/bin
    BUILDPACK_CACHE: /home/work/dea_ng/packages/buildpack_cache
  memory_limit_mb: 10240
  disk_limit_mb: 20480
  max_staging_duration: 900 # 15 minutes

dea_ruby: /usr/local/bin/ruby

# For Go-based directory server
directory_server:
  v1_port: 4385
  v2_port: 5678
  file_api_port: 1234
  streaming_timeout: 10
  logging:
    level: info
    file: /home/work/dea_ng/log/dir_server.log
logging:
    level: info
    file: /home/work/dea_ng/log/dea.log
stacks:
  - lucid64

# clean droplet if droplet stop or crash
clean_droplet: false

# Hook scripts for droplet start/stop
# hooks:
#   before_start: path/to/script
#   after_start: path/to/script
#   before_stop: path/to/script
#   after_stop: path/to/script
status:
  port: 8091
  user: test
  password: test

enable_sshd: true

org_data:
  src_prefix: /home/work/appdata
  bind_mounts:
    -
      name: mfs 
      mode: "rw"
    -
      name: jdata

app_workspace:
  user: work

